### ISSUE TITLE
Issue running app new

### ISSUE THREAD

**Issue by chrisanderton** [heroku/predictionio-buildpack#11]
parallel-leadscoring-develop> heroku run "pio app new test-pio-leadscoring-app" -a test-pio-server
Running pio app new test-pio-leadscoring-app on ⬢ test-pio-server... up, run.2491 (Free)
Autoset Spark memory params for web process: --executor-memory 256m --driver-memory 256m 
Autoset Spark memory params for training: --executor-memory 256m --driver-memory 256m 
/app/.profile.d/pio-render-configs.sh: line 3: /app/pio-engine/PredictionIO-dist/conf/core-site.xml: No such file or directory

**Comment by chrisanderton** [comment]
The profile.d script attempts to process a file that doesn't exist on event server (engine.json doesn't exist, so pio-engine directory won't exist)

Adding a check to the profile script to only run on existence solves the immediate issue (https://github.com/chrisanderton/predictionio-buildpack/blob/master/.profile.d/pio-render-configs.sh) but i don't know this well enough to know what other issues there may be

**Comment by mars** [comment]
Thanks for filing this issue @chrisanderton. It is the simple fix you suggested.
