### ISSUE TITLE
Release command failed

### ISSUE THREAD

**Issue by DanielShox** [heroku/predictionio-buildpack#13]
Hi,

The release cmd fails for me with the Heroku logs saying:

```
[ERROR] [SparkContext] Error initializing SparkContext.
app[release.7153]: Exception in thread "main" java.lang.IllegalArgumentException: System memory 249561088 must be at least 4.718592E8. Please use a larger heap size.
```

I see in the instructions that I need to scale up but do I need to do this prior to deploy?

Also when I try : heroku run train it can't find the file....

```
Running train on ⬢ sdo-dc-pioengine... up, run.9921 (Free)
bash: bin/heroku-buildpack-pio-train: No such file or directory
```

Thanks.

**Comment by mars** [comment]
Hi @DanielShox,

The Free dyno size is too small. Per the README instructions, scale it up.

Re: the second error, since the app has not deployed/released successfully yet, the pio commands are not available yet.

**Comment by DanielShox** [comment]
Great, just double checking before I scale! Thanks for the quick response.

**Comment by arctana** [comment]
Hi,
The release cmd failed for me as well. I scaled up the dyno as per the instruction (shouldn't we do that before the release?) but I still have the following error:
"bash: bin/heroku-buildpack-pio-train: No such file or directory"

I can see that the last release failed:
=== pio-engine Releases - Current: v4
v5  Deploy 94f165b release command failed

but when I re-run the command "git push heroku master" he is telling me that "Everything up-to-date".

This is what the log (heroku logs -t --app pio-engine) is telling me
...
app[release.1727]: [ERROR] [SparkContext] Error initializing SparkContext.
app[release.1727]: Exception in thread "main" java.lang.IllegalArgumentException: System memory 249561088 must be at least 4.718592E8. Please use a larger heap size. 
...

I am stuck. Please help.

**Comment by mars** [comment]
@arctana You can retry the release with the Heroku CLI plugin, [heroku-releases-retry](https://github.com/heroku/heroku-releases-retry). An alternative solution is to push another commit to trigger a whole new build, after scaling-up: `git commit --allow-empty -m deploy && git push heroku master`.

Background: there's currently a catch-22 in scaling the dynos for PredictionIO. You can't scale dynos until the [processes are defined](https://devcenter.heroku.com/articles/procfile), once the first release completes. Conversely the PredictionIO train-on-release won't complete successfully until the dynos are scaled up!

**Comment by arctana** [comment]
Haha, it's alive!
(I tried the second solution and it worked)
Thanks
