### ISSUE TITLE
No access to app "classi"

### ISSUE THREAD

**Issue by jennakwon06** [heroku/predictionio-buildpack#2]
Hello,

While running below commands

```
heroku run 'pio app new classi' --app $eventserver_name
#
# Use the returned access key for `$pio_app_access_key`
#
heroku config:set \
  PIO_EVENTSERVER_HOSTNAME=$eventserver_name.herokuapp.com \
  PIO_EVENTSERVER_PORT=80 \
  PIO_EVENTSERVER_ACCESS_KEY=$pio_app_access_key \
  PIO_EVENTSERVER_APP_NAME=classi
```

I get  an error: ▸    You do not have access to the app classi.

How may I go about resolving this issue?

Thank you!

**Comment by mars** [comment]
Which command returns that error?

It sounds like you're using "classi" for the `$eventserver_name`, when that value should be the name of your unique eventserver. Make sure `$eventserver_name` is replaced with that Heroku app name.

**Comment by mars** [comment]
…or maybe the wrong value is used for the PIO access key `$pio_app_access_key`. Did you replace that value with the access key returned in the first command?

**Comment by mars** [comment]
Based on a message from @jennakwon06 on the Mailing List user@predictionio.incubator.apache.org, this configuration issue was resolved.

**Comment by kamipatel** [comment]
Hi, I am getting this issue "You do not have access to the app kamapp"
heroku config:set PIO_EVENTSERVER_HOSTNAME=piotwoserver.herokuapp.com PIO_EVENTSERVER_ACCESS_KEY=Dyl557kXhgThKijXe1ImWOoMQ_bmyyacrb6quU-2pzET6V8i8t-CK_GDfC1LT98U PIO_EVENTSERVER_APP_NAME=kamapp PIO_EVENTSERVER_PORT=80 --app kamapp
Just not working.... Please help.
