### ISSUE TITLE
Slug size

### ISSUE THREAD

**Issue by pelim** [heroku/predictionio-buildpack#32]
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing...
remote:  !     Compiled slug size: 325.8M is too large (max is 300M).
remote:  !     See: http://devcenter.heroku.com/articles/slug-size
remote: 
remote:  !     Push failed

**Comment by mars** [comment]
This error will not occur when you use the predictionio-buildpack master branch, per the instructions..

Unfortunately, deploying forks or branches of this buildpack is not supported for the general public, unless you contact Heroku support to have the slug size limit lifted for your app.

We hope to one day see these limits lifted for the platform, but until then, predictionio-buildpack master branch is the only one generally deployable.

**Comment by pelim** [comment]
@dzuelke it is possible to increase the slug size for my account?

**Comment by dzuelke** [comment]
Please contact support @pelim
