### ISSUE TITLE
v7.1.0 Breakthrough compile error

### ISSUE THREAD

**Issue by dannyshox** [heroku/predictionio-buildpack#33]
Hi,

Getting this error when trying to push the Universal Recommender to heroku following these instructions: 

https://github.com/heroku/predictionio-buildpack/releases/tag/v7.1.0

`remote:        [INFO] [Engine$] [error] /app/pio-engine/src/main/scala/EsClient.scala:215: Unmatched closing brace '}' ignored here
remote:        [INFO] [Engine$] [error]         }
remote:        [INFO] [Engine$] [error]         ^
remote:        [INFO] [Engine$] [error] /app/pio-engine/src/main/scala/EsClient.scala:239: ';' expected but 'finally' found.
remote:        [INFO] [Engine$] [error]         } finally {
remote:        [INFO] [Engine$] [error]           ^
remote:        [INFO] [Engine$] [error] two errors found
remote:        [INFO] [Engine$] [error] (compile:compile) Compilation failed
remote:        [INFO] [Engine$] [error] Total time: 42 s, completed May 3, 2017 8:05:42 AM

remote:        [ERROR] [Engine$] Return code of build command: /app/pio-engine/PredictionIO-dist/sbt/sbt  package assemblyPackageDependency is 1. Aborting.
remote:        [INFO] [Engine$] Looking for an engine...`

**Comment by mars** [comment]
Hi @dannyshox , the support for UR is not documented yet, and it's complicated because of all the special config required: a fork of PIO, a fork of UR, specific ElasticSearch.

Are you trying to deploy https://github.com/heroku/predictionio-engine-ur ?

**Comment by dannyshox** [comment]
Hi @mars Thanks. 

No, I hadn't seen that repo. I was following your other instructions from the v7.1.0 Breakthrough readme....

It's now building successfully but I get the slug size error that's been referred to here: #32 

You mention 'This error will not occur when you use the predictionio-buildpack master branch, per the instructions.' .... but I'm using the buildpack's master branch git URL and it's still giving the error.

Is the only other option to get the slug size limit removed?

Thanks.

**Comment by mars** [comment]
The slug size will not be a problem as long as it's set to *exactly*:

```
https://github.com/heroku/predictionio-buildpack.git
```

Verify this for your engine with the command `heroku buildpacks`. That precise URL should be in position 2 for an engine.
