### ISSUE TITLE
How do you run the eventserver and an engine in one app?

### ISSUE THREAD

**Issue by djones** [heroku/predictionio-buildpack#47]
I wasn't quite able to figure this one out. It looks like you get different modes depending on which environment vars are set.

Ideally I'd like to run the event server and an engine on one web process, and spin up large one-off dynos for training.

If that's not possible, what is the minimum app/dyno architecture that works here? The demo data works on one dyno because it loads hardcoded data in directly and doesn't appear to use the event server. It's a bit unclear how you go from using the demo data to using this in production.

**Comment by djones** [comment]
P.S. Thanks for the sweet buildpack!

**Comment by mars** [comment]
Howdy @djones 

I have two answers to your question, depending on where the PIO engine is deployed.

Heroku Common Runtime
--------------------------
To be useful, an eventserver must be deployed as a separate app. See the docs for [running eventserver on Heroku](https://github.com/heroku/predictionio-buildpack/blob/master/CUSTOM.md#user-content-eventserver).

Heroku Private Spaces
-----------------------
In addition to the above separate app approach, another technique is possible using the Private Space's private network. This is only useful if the client(s) of the Eventserver REST API is in the same Private Space. You may define a new process type in the [`Procfile`](https://devcenter.heroku.com/articles/procfile) to run as a worker process:

```
web: bin/heroku-buildpack-pio-web
train: bin/heroku-buildpack-pio-train
release: bin/heroku-buildpack-pio-release
eventserver: pio eventserver --port 7070
```

Once that Procfile is deployed, other apps in the Private Space may reach that Eventserver via [DNS registry](https://devcenter.heroku.com/articles/dyno-dns-service-discovery) name, like:

```
http://eventserver.$APP_NAME.app.localspace:7070
```

✏️ *Replace `$APP_NAME` with the Heroku app's name.*

**Comment by djones** [comment]
Ah ok that makes sense @mars!

OK so just to run something by you... the min hosting infrastructure required to use this in a serious way (using Heroic Common Runtime) would be something like this:

Always running:

* ElasticSearch - e.g. [Bonsai](https://elements.heroku.com/addons/bonsai)
* PostgreSQL - e.g. [Heroku Postgres](https://www.heroku.com/postgres)
* Eventserver - running on a dyno
* An engine of choice - running on a dyno

One-off runs:

* Training - running on ideally a very large dyno

Is that right?

**Comment by mars** [comment]
Yes @djones, those are all the components needed to deploy PredictionIO. Of course the Eventserver piece is considered optional, depending on the data flow requirements for a given application.
