### ISSUE TITLE
Private Spaces DB

### ISSUE THREAD

**Issue by dannyshox** [heroku/predictionio-buildpack#48]
Hi,

Having trouble getting the JDBC driver to pull data from a private spaces PostGres DB on Heroku. 

The DB in question is attached to another App (this app being the one using the JDBC) in the same Private Space.

Is there support for this ?

Thanks.

**Comment by mars** [comment]
Not sure I understand the problem. Is there an error message? What are you doing (command or code) when it fails?

Also, private databases cannot be accessed from outside their Private Space accept via `heroku psql`.

**Comment by dannyshox** [comment]
Heroku-App-A & Heroku-App-Pio are in the same Private Space and I have Heroku-App-A's DB attached to Heroku-App-Pio ....

The code is as follows:

```
   var user62FeaturesRDD: RDD[Org62User] = null

    try {
      featuresRDD = new JdbcRDD(sc, DataSource.conn, featuresQuery, Long.MinValue, Long.MaxValue, 1, featuresMapRow).cache()
    } catch {
      case e =>
        e.printStackTrace
    }

object DataSource {
  @transient lazy val logger = Logger[this.type]

  def conn() = {
    val config = Storage.getConfig("PGSQL").get

    DriverManager.getConnection(
      config.properties("URL"),
      config.properties("USERNAME"),
      config.properties("PASSWORD")
    )
  }

  def jdbcRDD[T: ClassTag](sc: SparkContext, query: String, mapRow: ResultSet => T): RDD[T] = {
    new JdbcRDD(sc, conn, query, Long.MinValue, Long.MaxValue, 1, mapRow).cache()
  }

}
```
This doesn't throw an error during the try/catch .... Works fine on a cloned DB locally (heroku pg:pull)

**Comment by mars** [comment]
Where is this code located? When is it invoked?

**Comment by mars** [comment]
Sorry, I now see it's in DataSource.

There's nothing here that stands out as wrong. If it doesn't throw an error, then how does it malfunction? Does it hang or return empty data? Can you access that DB from a one-off dyno in `heroku run bash`?

**Comment by dannyshox** [comment]
Hi Mars, sorry for delay. Yes it was returning an empty RDD & I could access the DB from a one-off dyno but I've since discovered an underlying issue with the data - it was being encrypted without my knowledge! Pretty sure this is the issue. Thanks
